### ISSUE TITLE
内置浏览器无法加载，网页在正常浏览器能正常浏览，软件内置的无限加载

### ISSUE THREAD

**Issue by sakana164** [caorushizi/m3u8-downloader#12]
![image](https://user-images.githubusercontent.com/76257039/179967656-61f18a25-4fd0-4af6-a9cb-2c10c134bd50.png)
内置浏览器无法加载，网页在正常浏览器能正常浏览，软件内置的无限加载

**Comment by caorushizi** [comment]
应该是开了代理，百度开代理就打不开了
