### ISSUE TITLE
点击“新建下载”没有反应

### ISSUE THREAD

**Issue by feishi312** [caorushizi/m3u8-downloader#14]
# 点击“新建下载”没有反应，版本1.1.5
![screenshots](https://user-images.githubusercontent.com/38391659/200353154-d8f1847b-1dec-4c2f-801d-a8a63d6b04c1.gif)

**Comment by caorushizi** [comment]
好的，我看下

**Comment by feishi312** [comment]
> 好的，我看下

过了段时间，我今天发现点击“新建下载”等设置又可以了，奇怪。
