### ISSUE TITLE
是否考虑换用nilaoda新的M3U8DL项目

### ISSUE THREAD

**Issue by LennoC** [caorushizi/m3u8-downloader#45]
原m3u8dl_cli项目作者推出了新的跨平台[N_m3u8DL-RE](https://github.com/nilaoda/N_m3u8DL-RE)，可以考虑换用该CLI。测试体验新的RE更快，而且标榜跨平台可用。

**Comment by caorushizi** [comment]
直接换用新的可能会有坑，我还没有看过新的代码。可能后续版本会更新。

**Comment by caorushizi** [comment]
2.1.0 更新

**Comment by caorushizi** [comment]
@LennoC 昨天试了一下，windows上的 RE 还是有点慢。等后面慢慢完善吧。

**Comment by LennoC** [comment]
> @LennoC 昨天试了一下，windows上的 RE 还是有点慢。等后面慢慢完善吧。

是哪方面的慢呢？我下了一个剧集的几个视频，感觉RE比CLI还是更快的。

**Comment by caorushizi** [comment]
我昨天试了几个视频，中间会中断，中断后必须手动暂停开启，才能恢复。相同视频相对于cli 慢很多，等 re 发了稳定版本之后再迁移吧，目前来说我没有发现 cli 的很明显的问题。

**Comment by caorushizi** [comment]
我昨天 build 了一版，你试试 https://github.com/caorushizi/m3u8-downloader/suites/14761273535/artifacts/839286380
