### ISSUE TITLE
[建议]下载列表加一个排序-倒序功能

### ISSUE THREAD

**Issue by LennoC** [caorushizi/m3u8-downloader#51]
[建议]下载列表加一个排序-倒序功能
一般我们在提取剧集链接时是顺序列表内容过去提取的，希望下载时也能够是顺序下载。现在默认的话就是顺序录入下载链接，开始下载就变成倒序下载。 
eg. 剧集1-8，下载列表此时就是8-1，下载也会是从8向1倒序下载。
加一个倒序功能，就能够按照剧集列表下载了。

**Comment by caorushizi** [comment]
done.
