### ISSUE TITLE
你好，想问下，目前下载这块

### ISSUE THREAD

**Issue by zhuibo66** [caorushizi/m3u8-downloader#7]
目前electron是由关于专门的下载的方法，win.webContents.downloadURL(url)，我看项目中好像不是用这个下载，而且调用了一个m3u8的下载器，是这个方法有什么弊端吗？

我自己目前试了下，好像是不能自定义头部的，目前我自己测试了下是http下载自定义头部能下载，https不能加入referer，目前不太清楚是什么原因

**Comment by caorushizi** [comment]
调用的下载器是做了很多额外的处理的，详情可以看下这个下载工具的实现 https://github.com/nilaoda/N_m3u8DL-CLI
