### ISSUE TITLE
Mac下载失败

### ISSUE THREAD

**Issue by Acheng97** [caorushizi/m3u8-downloader#78]
系统：Mac m2 
版本：[media-downloader-setup-2.0.3-beta.3.dmg]
下载链接：https://vip.ffzy-online3.com/20230202/10532_0d5f6505/index.m3u8
<img width="884" alt="image" src="https://github.com/caorushizi/m3u8-downloader/assets/65265814/7015c91a-fe60-44b1-876d-21d77c613669">

**Comment by Acheng97** [comment]
而且，打开软件比较慢

**Comment by caorushizi** [comment]
下载失败的问题已经修复，会在下个版本更新。Mac 上加载比较慢的问题不影响使用，后续集中时间优化。
