### ISSUE TITLE
关于【批量解析】支持

### ISSUE THREAD

**Issue by adminpass** [caorushizi/m3u8-downloader#8]
**优化建议：**

1. 任务列表**待下载**任务支持重命名，即增加重命名编辑
 - 当前解析器无法识别流媒体网站剧集名称，即任务栏名字都是重复的
2. 支持批任务导入，主要为**待解析URL**、**保存文件名称**
- 主要是为批量下载剧集动画需求，待解析URL：【免会员解析链前缀+优爱腾URL】
- 考虑到第三方解析的m3u8有时效性，所以最好批导入能选择立即下载

**Comment by adminpass** [comment]
close

**Comment by caorushizi** [comment]
后面有时间做吧，有什么建议都可以提出来的~
