### ISSUE TITLE
下载数据收集？？

### ISSUE THREAD

**Issue by adminpass** [caorushizi/m3u8-downloader#9]
**https://h5.udrig.com/app/v1**
### 这是在收集下载数据？

![1340](https://user-images.githubusercontent.com/7523220/150937772-6db85b90-a6cd-4eea-b2b1-a2104d8f6d0e.jpg)
![161643](https://user-images.githubusercontent.com/7523220/150938034-c6401194-8429-4395-a4d0-b5c0a28444b3.jpg)

**Comment by caorushizi** [comment]
今天晚上我会更新一版，争得用户同意再打点～

**Comment by caorushizi** [comment]
能不能留个qq我加你

**Comment by caorushizi** [comment]
1.1.3 release
